### ISSUE TITLE
how to get paper describing this solution?

### ISSUE THREAD

**Issue by feiwofeifeixiaowo** [andreapatane/SiameseNet-PhNet2018Challenge#1]
**Hi andreapatane,** 
Thanks for your wonderful code,  this help me a lot in PSG singal process and modeling.
how to get access the paper about  your solution?

**Comment by andreapatane** [comment]
Hey feiwofeifeixiaowo,

Sorry for answering late. I just added a link to the paper in the readme file in the repo. You might find useful also this paper which relies on a similar approach: http://qav.comlab.ox.ac.uk/papers/pk18.pdf

Cheers,
Andrea

**Comment by feiwofeifeixiaowo** [comment]
This [paper]( http://qav.comlab.ox.ac.uk/papers/pk18.pdf) is also very useful.
Thanks andreapatane ^_^.

**Comment by andreapatane** [comment]
No problem, let me know if I can be helpful in any other way.
Cheers
