### ISSUE TITLE
how can I calculate score in test set?

### ISSUE THREAD

**Issue by ALein** [andreapatane/SiameseNet-PhNet2018Challenge#3]
After I downloaded the relevant data set, I found that the tTraining set provides annotation file, which can calculate auprc and auroc, while test set only provides original data, but no annotation file. After training my model, how can I calculate score in test set?

**Comment by andreapatane** [comment]
Hi - the dataset is provided by the physionet challenge organiser. They did not released the test set so to avoid bad ML practice. Get in touch with them for additional details, more info: https://physionet.org/content/challenge-2018/1.0.0/

I would reccomend to thourougly validate your model in a leave-one-user-out kind of settings with the data available, before submitting an entry for test set validation (if they challenge organiser still allow that)
